# -*- coding: utf-8 -*-
"""EnglishPlayers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17rZ-HFFWQhfFzercCN_WWhp7igxxxGZu
"""

from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd

p1=pd.read_csv("player1.csv", sep=',', encoding="latin1")

p2=pd.read_csv("player2.csv", sep=',', encoding="latin1")

p3=pd.read_csv("players3.csv", sep=',', encoding="latin1")

p4=pd.read_csv("players4.csv", sep=',', encoding="latin1")

p5=pd.read_csv("players5.csv", sep=',', encoding="latin1")

tot = pd.concat([p1, p2,p3,p4,p5],sort=False)
len(tot)

tot.to_csv("EnglishPlayer.csv")